spring:
  application:
    name: my-consumer

demo:
  service:
    version: 1.0.0

#embedded:
#  zookeeper:
#    port: 2181

dubbo:
  registry:
    address: nacos://198.18.66.41:8848
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache